apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: lab18
  name: cron-crawler
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: write-file
            image: chashaoan/auto_crawler:2.0.7
            volumeMounts:
            - name: history-dir
              mountPath: /var/log/history
          restartPolicy: OnFailure
          volumes:
          - name: history-dir
            persistentVolumeClaim:
              claimName: pvc-lab18