apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: lab18-crawler-exporter
  name: lab18-crawler-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: lab18-crawler-exporter
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.network/app-network: "true"
        io.kompose.service: lab18-crawler-exporter
    spec:
      containers:
        - image: chashaoan/crawler_exporter:1.0.1
          name: lab18-crawler-exporter
          ports:
            - containerPort: 8111
            - containerPort: 8777
          resources: {}
      restartPolicy: Always
status: {}
